# FAI Homework 2

**FBA Quant 이의형**

---

## Problem 1. KRX Database Data

You should create a simple python package to get the data from http://data.krx.co.kr/ easily.  
The package should be named as krx and have a class named 'WebSource'.  
Then we can import it as 'from krx import WebSource'.

The complete library should have followings.

In [1]:
from krx import WebSource

kws = WebSource()

**(a)** A method to set frequency of multiple requests.  
(If you don't have some sleep between requests, the host will block your ip address.)

In [2]:
kws.set_freq(1)
kws.freq

Set freq: 1

1

**(b)**
A method to get the index constituents data.  
The method should have parameters; 'index_name', 'start', 'end'.  
Getting all indices is quite annoying, so it is okay to implement only 'KOSPI', 'KOSPI200', 'KOSDAQ', and 'KOSDAQ150'.  
Choose the best data structure to return.

In [3]:
kospi200 = kws.get_index_stocks_in_period(index_name='KOSPI200', start='2023-08-01', end='2023-08-18')
kospi200

,A098120,A009520,A095570,A006840,A282330,A027410,A138930,A001465,A001460,A001045,...,A084110,A145020,A024060,A010240,A189980,A000545,A000540,A003280,A037440,A238490
2023-08-01,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-02,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-03,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-04,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-07,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-08,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-09,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-10,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-11,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-14,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-16,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-17,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-18,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**(c)**
A method to get the historical daily OHLCV data.  
The method should have parameters; 'stock_code'(A000000), 'start', 'end'.  
Please return pandas.DataFrame.

In [4]:
samsung_ohlcv = kws.get_ohlcv('A005930', start='2023-08-01', end='2023-08-18')
samsung_ohlcv

          date  adj_open  adj_high  adj_low  adj_close    volume
0   2023/08/01     70100     71200    70000      71100  12299254
1   2023/08/02     70700     71000    69800      69900  13835020
2   2023/08/03     69900     70200    68500      68800  20087090
3   2023/08/04     68800     69100    68200      68300  12360193
4   2023/08/07     67700     69200    67600      68500  10968505
5   2023/08/08     69000     69100    67400      67600  14664709
6   2023/08/09     68000     69600    67900      68900  17259673
7   2023/08/10     68300     68500    67800      68000  10227311
8   2023/08/11     68400     68800    67500      67500   9781038
9   2023/08/14     67500     67900    66900      67300   9352343
10  2023/08/16     66700     67100    66300      67000  13174578
11  2023/08/17     66300     66800    66000      66700  10778652
12  2023/08/18     66000     66700    65800      66300  11745006

**(d)**
A method to get the OHLCV data for a given universe.  
The method should have para meters; 'index_name', 'start', 'end'.  
(This method returns OHLCV data of all stocks listed in a given index_name during the period.)  
Choose the best data structure to return.

In [5]:
kospi200_ohlcv = kws.get_index_stocks_ohlcv(index_name='KOSPI200', start='2023-08-01', end='2023-08-18')
kospi200_ohlcv['adj_close'].head(10)

,A098120,A009520,A095570,A006840,A282330,A027410,A138930,A001465,A001460,A001045,...,A084110,A145020,A024060,A010240,A189980,A000545,A000540,A003280,A037440,A238490
2023-08-01,NaN,NaN,NaN,NaN,172700.0,NaN,6870.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-02,NaN,NaN,NaN,NaN,170200.0,NaN,6710.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-03,NaN,NaN,NaN,NaN,171200.0,NaN,6680.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-04,NaN,NaN,NaN,NaN,169400.0,NaN,6750.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-07,NaN,NaN,NaN,NaN,170300.0,NaN,6750.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-08,NaN,NaN,NaN,NaN,171600.0,NaN,6770.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-09,NaN,NaN,NaN,NaN,165300.0,NaN,6730.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-10,NaN,NaN,NaN,NaN,170000.0,NaN,6660.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-11,NaN,NaN,NaN,NaN,167400.0,NaN,6610.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-14,NaN,NaN,NaN,NaN,169200.0,NaN,6640.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

---

## Problem 2. Binance Public Data

You should create a simple python package to get the data from https://data.binance.vision/ easily.  
The package should be named as binance and have a class named 'PublicData'.  
Then we can import it as 'from binance import PublicData'.

In [6]:
from binance import PublicData

bpd = PublicData()

**(a)**
A method to set frequency of multiple requests.  
(If you don't have some sleep between requests, the host will block your ip address.)

In [7]:
bpd.set_freq(0.1)
bpd.freq

Set freq: 0.1

0.1

**(b)**
A method to get list of symbols of USDT futures daily kline(OHLCV) data from  
(https://data.binance.vision/?prefix=data/futures/um/daily/klines/)

In [8]:
tickers = bpd.get_usdt_tickers()
tickers

['1000BTTCUSDT',
 '1000FLOKIUSDT',
 '1000LUNCUSDT',
 '1000PEPEUSDT',
 '1000SHIBUSDT',
 '1000XECUSDT',
 '1INCHUSDT',
 'AAVEUSDT',
 'ACHUSDT',
 'ADAUSDT',
 'AGIXUSDT',
 'AGLDUSDT',
 'AKROUSDT',
 'ALGOUSDT',
 'ALICEUSDT',
 'ALPHAUSDT',
 'AMBUSDT',
 'ANCUSDT',
 'ANKRUSDT',
 'ANTUSDT',
 'APEUSDT',
 'API3USDT',
 'APTUSDT',
 'ARBUSDT',
 'ARKMUSDT',
 'ARPAUSDT',
 'ARUSDT',
 'ASTRUSDT',
 'ATAUSDT',
 'ATOMUSDT',
 'AUDIOUSDT',
 'AVAXUSDT',
 'AXSUSDT',
 'BAKEUSDT',
 'BALUSDT',
 'BANDUSDT',
 'BATUSDT',
 'BCHUSDT',
 'BELUSDT',
 'BLUEBIRDUSDT',
 'BLURUSDT',
 'BLZUSDT',
 'BNBUSDT',
 'BNTUSDT',
 'BNXUSDT',
 'BTCDOMUSDT',
 'BTCSTUSDT',
 'BTCUSDT',
 'BTSUSDT',
 'BTTUSDT',
 'BZRXUSDT',
 'C98USDT',
 'CELOUSDT',
 'CELRUSDT',
 'CFXUSDT',
 'CHRUSDT',
 'CHZUSDT',
 'CKBUSDT',
 'COCOSUSDT',
 'COMBOUSDT',
 'COMPUSDT',
 'COTIUSDT',
 'CRVUSDT',
 'CTKUSDT',
 'CTSIUSDT',
 'CVCUSDT',
 'CVXUSDT',
 'DARUSDT',
 'DASHUSDT',
 'DEFIUSDT',
 'DENTUSDT',
 'DGBUSDT',
 'DODOUSDT',
 'DODOXUSDT',
 'DOGEUSDT',
 'DOTECOUSDT',
 'DOTUSDT',
 'DUSKUSDT',
 'DYDXUSDT',
 'EDUUSDT',
 'EGLDUSDT',
 'ENJUSDT',
 'ENSUSDT',
 'EOSUSDT',
 'ETCUSDT',
 'ETHUSDT',
 'FETUSDT',
 'FILUSDT',
 'FLMUSDT',
 'FLOWUSDT',
 'FOOTBALLUSDT',
 'FTMUSDT',
 'FTTUSDT',
 'FXSUSDT',
 'GALAUSDT',
 'GALUSDT',
 'GMTUSDT',
 'GMXUSDT',
 'GRTUSDT',
 'GTCUSDT',
 'HBARUSDT',
 'HFTUSDT',
 'HIGHUSDT',
 'HNTUSDT',
 'HOOKUSDT',
 'HOTUSDT',
 'ICPUSDT',
 'ICXUSDT',
 'IDEXUSDT',
 'IDUSDT',
 'IMXUSDT',
 'INJUSDT',
 'IOSTUSDT',
 'IOTAUSDT',
 'IOTXUSDT',
 'JASMYUSDT',
 'JOEUSDT',
 'KAVAUSDT',
 'KEEPUSDT',
 'KEYUSDT',
 'KLAYUSDT',
 'KNCUSDT',
 'KSMUSDT',
 'LDOUSDT',
 'LENDUSDT',
 'LEVERUSDT',
 'LINAUSDT',
 'LINKUSDT',
 'LITUSDT',
 'LPTUSDT',
 'LQTYUSDT',
 'LRCUSDT',
 'LTCUSDT',
 'LUNA2USDT',
 'LUNAUSDT',
 'MAGICUSDT',
 'MANAUSDT',
 'MASKUSDT',
 'MATICUSDT',
 'MAVUSDT',
 'MDTUSDT',
 'MINAUSDT',
 'MKRUSDT',
 'MTLUSDT',
 'NEARUSDT',
 'NEOUSDT',
 'NKNUSDT',
 'NMRUSDT',
 'NUUSDT',
 'OCEANUSDT',
 'OGNUSDT',
 'OMGUSDT',
 'ONEUSDT',
 'ONTUSDT',
 'OPUSDT',
 'OXTUSDT',
 'PENDLEUSDT',
 'PEOPLEUSDT',
 'PERPUSDT',
 'PHBUSDT',
 'QNTUSDT',
 'QTUMUSDT',
 'RADUSDT',
 'RAYUSDT',
 'RDNTUSDT',
 'REEFUSDT',
 'RENUSDT',
 'RLCUSDT',
 'RNDRUSDT',
 'ROSEUSDT',
 'RSRUSDT',
 'RUNEUSDT',
 'RVNUSDT',
 'SANDUSDT',
 'SCUSDT',
 'SEIUSDT',
 'SFPUSDT',
 'SKLUSDT',
 'SNXUSDT',
 'SOLUSDT',
 'SPELLUSDT',
 'SRMUSDT',
 'SSVUSDT',
 'STGUSDT',
 'STMXUSDT',
 'STORJUSDT',
 'STXUSDT',
 'SUIUSDT',
 'SUSHIUSDT',
 'SXPUSDT',
 'THETAUSDT',
 'TLMUSDT',
 'TOMOUSDT',
 'TRBUSDT',
 'TRUUSDT',
 'TRXUSDT',
 'TUSDT',
 'UMAUSDT',
 'UNFIUSDT',
 'UNIUSDT',
 'USDCUSDT',
 'VETUSDT',
 'WAVESUSDT',
 'WLDUSDT',
 'WOOUSDT',
 'XEMUSDT',
 'XLMUSDT',
 'XMRUSDT',
 'XRPUSDT',
 'XTZUSDT',
 'XVGUSDT',
 'XVSUSDT',
 'YFIIUSDT',
 'YFIUSDT',
 'YGGUSDT',
 'ZECUSDT',
 'ZENUSDT',
 'ZILUSDT',
 'ZRXUSDT']

**(c)**
A method to get the kline data of USDT futures.  
The method should have parameters; 'symbol', 'start', 'end'.  
Please return the result as pandas.DataFrame.

In [9]:
btcusdt_ohlcv = bpd.get_kline('BTCUSDT', '2023-08-01', '2023-08-18')
btcusdt_ohlcv

               open     high      low    close      volume
2023-08-01  29220.8  29735.0  28550.0  29701.2  442328.643
2023-08-02  29701.2  30059.9  28906.3  29170.1  491725.492
2023-08-03  29170.2  29440.0  28955.4  29180.2  251967.942
2023-08-04  29180.1  29323.8  28780.0  29101.1  229395.673
2023-08-05  29101.1  29145.0  28960.0  29057.7   82508.624
2023-08-06  29057.7  29199.0  28978.5  29075.9   103094.44
2023-08-07  29075.9  29274.5  28682.3  29202.7  297752.439
2023-08-08  29202.7  30250.0  29132.4  29759.0  459269.801
2023-08-09  29758.9  30149.7  29362.0  29572.8  362009.701
2023-08-10  29572.9  29729.8  29303.7  29443.7  234546.038
2023-08-11  29443.7  29565.1  29220.0  29415.5  179044.008
2023-08-12  29415.5  29470.0  29360.0  29420.7   56238.035
2023-08-13  29420.8  29463.0  29256.6  29293.3   84190.505
2023-08-14  29293.3  29686.7  29070.0  29419.5  295035.383
2023-08-15  29419.5  29492.1  29050.0  29188.8  191289.959
2023-08-16  29188.9  29257.4  28705.1  28714.4  272023.138
2023-08-17  28714.4  28775.9  24581.0  26609.7   868508.22
2023-08-18  26609.7  26818.0  25600.0  26042.1  522375.316

---